### ISSUE TITLE
Поменять шрифт на более читаемый, можно даже белый поставить, а то щас плохо видно

### ISSUE THREAD

**Issue by SnayChannel** [FrameMuse/StandoffMarket#53]
Поменять шрифт на более читаемый, можно даже белый поставить, а то щас плохо видно

- [ ] 

![image](https://user-images.githubusercontent.com/56320307/90451399-6509bb00-e0f4-11ea-9980-32f55934ad27.png)

**Comment by FrameMuse** [comment]
![image](https://user-images.githubusercontent.com/53980482/90543165-4f4cd200-e196-11ea-8d34-006f43b831a8.png)
