### ISSUE TITLE
Фиксануть длинные блоки в чате с продавцом

### ISSUE THREAD

**Issue by SnayChannel** [FrameMuse/StandoffMarket#54]
Фиксануть длинные блоки в чате с продавцом

- [ ] 

![image](https://user-images.githubusercontent.com/56320307/90451499-a13d1b80-e0f4-11ea-8017-ec158bf2da6e.png)

**Comment by FrameMuse** [comment]
![image](https://user-images.githubusercontent.com/53980482/90542993-07c64600-e196-11ea-9b96-9b11a0a04dd7.png)
