### ISSUE TITLE
Доработать открытие корзины, чтобы когда ты её открывал, не было видно кривого слайдера(или как называется это полоска :D), который скользит вниз-вверх 

### ISSUE THREAD

**Issue by SnayChannel** [FrameMuse/StandoffMarket#60]
Доработать открытие корзины, чтобы когда ты её открывал, не было видно кривого слайдера(или как называется это полоска :D), который скользит вниз-вверх 

[https://imgur.com/a/TWwtASR](url)

- [ ]

**Comment by FrameMuse** [comment]
Скроллбар* + он там нужен чтобы тем у кого экран меньше можно было скроллить
