### ISSUE TITLE
Заменить текст "История баланса" на "История вывода", а так же добавить текст если выводов еще не было:  "У Вас еще не было выводов средств с сайта!"

### ISSUE THREAD

**Issue by SnayChannel** [FrameMuse/StandoffMarket#64]
Заменить текст "История баланса" на "История вывода", а так же добавить текст если выводов еще не было:

"У Вас еще не было выводов средств с сайта!"

![image](https://user-images.githubusercontent.com/56320307/90453495-6b4e6600-e0f9-11ea-9988-ae30f7fad0f0.png)

**Comment by FrameMuse** [comment]
![image](https://user-images.githubusercontent.com/53980482/90515739-1dc30f00-e174-11ea-9690-fa6d7321c978.png)
