### ISSUE TITLE
Доработать окно с пополнением баланса, оно должно выглядеть так, как на скрине

### ISSUE THREAD

**Issue by SnayChannel** [FrameMuse/StandoffMarket#65]
Доработать окно с пополнением баланса, оно должно выглядеть так, как на скрине

![image](https://user-images.githubusercontent.com/56320307/90453638-d5ffa180-e0f9-11ea-995b-bb1a0c03e4ed.png)

- [ ]

**Comment by FrameMuse** [comment]
Вот так
![image](https://user-images.githubusercontent.com/53980482/90514702-94f7a380-e172-11ea-8026-c315b5e9fc54.png)
